[build]
  base    = ""
  command = "npm install && npx vite build"
  publish = "dist"

[build.environment]
  NODE_ENV = "development"

[[redirects]]
  from   = "/api/*"
  to     = "https://ikpokecatch-production.up.railway.app/api/:splat"
  status = 200
  force  = true
